package negocio;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item Remito.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class ItemRemito {
	private String detalleReparacion;
	private String detalleEquipo;
	private Equipo equipo;
	private int NroItemRemito;
	public String getDetalleReparacion() {
		return detalleReparacion;
	}
	public void setDetalleReparacion(String detalleReparacion) {
		this.detalleReparacion = detalleReparacion;
	}
	public String getDetalleEquipo() {
		return detalleEquipo;
	}
	public void setDetalleEquipo(String detalleEquipo) {
		this.detalleEquipo = detalleEquipo;
	}
	public Equipo getEquipo() {
		return equipo;
	}
	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}
	public int getNroItemRemito() {
		return NroItemRemito;
	}
	public void setNroItemRemito(int nroItemRemito) {
		NroItemRemito = nroItemRemito;
	}
}
