package negocio;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : itemReporte.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class itemReporte {
	private String nombrePieza;
	private int cantidadPieza;
	public String getNombrePieza() {
		return nombrePieza;
	}
	public void setNombrePieza(String nombrePieza) {
		this.nombrePieza = nombrePieza;
	}
	public int getCantidadPieza() {
		return cantidadPieza;
	}
	public void setCantidadPieza(int cantidadPieza) {
		this.cantidadPieza = cantidadPieza;
	}
}
