package model;

import java.util.Vector;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Modelo.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class Modelo {
	private int nroModelo;
	private String nombre;
	private Vector<Pieza> piezas;
	private String estado;
	private String descripcion;
	
	
	public Modelo(String nombre2, String descripcion, int codigo) {
		this.nombre=nombre2;
		this.descripcion=descripcion;
		this.nroModelo=codigo;
		this.piezas=new Vector<Pieza>();
		this.estado="activo";
	}
	public int getNroModelo() {
		return nroModelo;
	}
	public void setNroModelo(int nroModelo) {
		this.nroModelo = nroModelo;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public Vector<Pieza> getPiezas() {
		return piezas;
	}
	public void setPiezas(Vector<Pieza> piezas) {
		this.piezas = piezas;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public boolean modeloActivo() {
		return this.getEstado()=="activo";
	}
	public void darBajaModelo() {
		this.estado="inactivo";
		
	}
}
