package com.uade.seminario.tpo.model;

import com.uade.seminario.tpo.view.PiezaView;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pieza.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class Pieza {
	private int nroPieza;
	private String nombrePieza;
	private String descripcion;
	private String estado;
	public Pieza(int codPieza, String nombre, String descripcion2) {
		this.nroPieza=codPieza;
		this.nombrePieza=nombre;
		this.descripcion=descripcion2;
		this.estado="activo";
	}
	public int getNroPieza() {
		return nroPieza;
	}
	public void setNroPieza(int nroPieza) {
		this.nroPieza = nroPieza;
	}
	public String getNombrePieza() {
		return nombrePieza;
	}
	public void setNombrePieza(String nombrePieza) {
		this.nombrePieza = nombrePieza;
	}
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public boolean hayStock() {
		
		return false;
	}
	public void darBajaPieza() {
		setEstado("inactivo");
		
	}
	public PiezaView getView() {
		PiezaView piezaview=new PiezaView(getNroPieza(), getNombrePieza(), getDescripcion());
		return piezaview;
		
	}
}
