package com.uade.seminario.tpo.model;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import com.uade.seminario.tpo.view.ClienteView;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//


@Entity
@Table(name="cliente")
public class Cliente {
	private String nombre;
	private String apellido;
	public ClienteId id;
	private Date fechaNac;
	private String direccion;
	private String email;
	private String telefono;
	
	public Cliente(){
		
	}
	public Cliente(int nroDoc, String tipoDoc, String nombre2, String apellido2,
			String direccion, String mail, String fechaNac2, String tel) {
		this.nombre=nombre2;
		this.apellido=apellido2;
		this.direccion=direccion;
		this.fechaNac=new Date(Date.parse(fechaNac2));
		this.email=mail;
		this.telefono=tel;
		this.id = new ClienteId(nroDoc, tipoDoc);
		
	}

	public ClienteId getId() {
		return id;
	}
	
	public void setId(ClienteId id) {
		this.id = id;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getApellido() {
		return apellido;
	}
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
	public int getNroDoc() {
		return this.id.getNroDoc();
	}
	public void setNroDoc(int nroDoc) {
		this.id.setNroDoc(nroDoc);
	}
	public String getTipoDoc() {
		return this.id.getTipoDoc();
	}
	public void setTipoDoc(String tipoDoc) {
		this.id.setTipoDoc(tipoDoc);
	}
	public Date getFechaNac() {
		return fechaNac;
	}
	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public ClienteView getView() {
		// TODO Auto-generated method stub
		return null;
	}
	public String getDireccion() {
		return direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getTelefono() {
		return telefono;
	}
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
}
