package com.uade.seminario.tpo.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Equipo.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class Equipo {
	private int nroSerie;
	private Modelo modelo;
	private Cliente cliente;
	private Garantia garantia;
	private String estado;
	
	public Equipo(int nroEquipo, Modelo modelo2, Cliente cliente2,
			Garantia garantia2) {
		this.nroSerie=nroEquipo;
		this.modelo=modelo2;
		this.cliente=cliente2;
		this.garantia=garantia2;
		this.estado="inactivo";
	}
	public int getNroSerie() {
		return nroSerie;
	}
	public void setNroSerie(int nroSerie) {
		this.nroSerie = nroSerie;
	}
	public Modelo getModelo() {
		return modelo;
	}
	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}
	public Cliente getCliente() {
		return cliente;
	}
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
	public Garantia getGarantia() {
		return garantia;
	}
	public void setGarantia(Garantia garantia) {
		this.garantia = garantia;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
}
