package com.uade.seminario.tpo.model;
import java.sql.Date;
import java.util.Vector;

import com.uade.seminario.tpo.view.objectView.OrdenReparacionView;
import com.uade.seminario.tpo.view.objectView.TareaReparacionView;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Orden Reparacion.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class OrdenReparacion {
	private int nroOrden;
	private Vector<TareaReparacion> itemsReparacion;
	private Equipo equipo;
	private Date fecha;
	private String estado;
	private String descripcionFallas;
	private boolean estaEnGarantiaFisica;
	private boolean repararDeTodosModos;
	private int prioridad;
	
	
	public OrdenReparacion(int nroOrden2) {
		this.nroOrden=nroOrden2;
		this.itemsReparacion=new Vector<TareaReparacion>();
		this.equipo=null;
		this.fecha=null;
		this.estado=null;
	}
	public int getNroOrden() {
		return nroOrden;
	}
	public void setNroOrden(int nroOrden) {
		this.nroOrden = nroOrden;
	}
	public Vector<TareaReparacion> getItemsReparacion() {
		return itemsReparacion;
	}
	public void setItemsReparacion(Vector<TareaReparacion> itemsReparacion) {
		this.itemsReparacion = itemsReparacion;
	}
	public Equipo getEquipo() {
		return equipo;
	}
	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}
	public Date getFecha() {
		return fecha;
	}
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	public boolean esTuEquipo(int nroSerieEquipo) {
		return this.equipo.getNroSerie()==nroSerieEquipo;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public boolean estadoAReparar() {
		return estado.equals("A reparar");
	}
	public OrdenReparacionView getView() {
		return new OrdenReparacionView(getNroOrden(),getDescripcionFallas(),getEquipo(),getEstado(),getFecha(),getItemsReparacion(),getPrioridad(),isRepararDeTodosModos(),isEstaEnGarantiaFisica());
	}
	public Vector<TareaReparacionView> listarTareasView() {
		Vector<TareaReparacionView> tareas=new Vector<TareaReparacionView>();
		
		for (TareaReparacion tarea : itemsReparacion) {
			if(tarea.estaActiva())
			tareas.add(tarea.getView());
		}
		return tareas;
	}
	public Vector<TareaReparacion> listarTareas() {
		return this.itemsReparacion;
	}
	public void listaPiezas() {
		Vector<TareaReparacion> tareas=listarTareas();
		for (TareaReparacion tareaReparacion : tareas) {
			tareaReparacion.listaPiezas();
		}
		
	}
	public void agregarItemReparacion(TareaReparacion tarea) {
		this.itemsReparacion.add(tarea);
		
	}
	public TareaReparacion obtenerTarea(int nroTarea) {
		for (TareaReparacion tarea : itemsReparacion) {
			if(tarea.getNroItemReparacion()==nroTarea)
				return tarea;
		}
		return null;
	}
	public void setDescripcionFallas(String fallas) {
		this.descripcionFallas=fallas;
		
	}
	public String getDescripcionFallas() {
		return this.descripcionFallas;
		
	}
	public boolean isEstaEnGarantiaFisica() {
		return estaEnGarantiaFisica;
	}
	public void setEstaEnGarantiaFisica(boolean estaEnGarantiaFisica) {
		this.estaEnGarantiaFisica = estaEnGarantiaFisica;
	}
	public boolean isRepararDeTodosModos() {
		return repararDeTodosModos;
	}
	public void setRepararDeTodosModos(boolean repararDeTodosModos) {
		this.repararDeTodosModos = repararDeTodosModos;
	}
	public int getPrioridad() {
		return prioridad;
	}
	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}
	public TareaReparacionView obtenerTareaView(int nroTarea) {
		for (TareaReparacion tarea : itemsReparacion) {
			if(tarea.getNroItemReparacion()==nroTarea)
				return tarea.getView();
		}
		return null;
	}
}
