package com.uade.seminario.tpo.view.objectView;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : itemReporte.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class ItemReporteView {
	private String descripcionPieza;
	private int cantidadPieza;
	private int nroPieza;
	
	public int getNroPieza() {
		return nroPieza;
	}
	public void setNroPieza(int nroPieza) {
		this.nroPieza = nroPieza;
	}
	public ItemReporteView(){//No tiene vectores a inicializar
		
	}
	public ItemReporteView(Integer nroPieza, String descripcion, Integer cantidad) {
		this.cantidadPieza=cantidad;
		this.descripcionPieza=descripcion;
		this.nroPieza=nroPieza;
	}
	public String getDescripcionPieza() {
		return descripcionPieza;
	}
	public void setDescripcionPieza(String descripcion) {
		this.descripcionPieza = descripcion;
	}
	public int getCantidadPieza() {
		return cantidadPieza;
	}
	public void setCantidadPieza(int cantidadPieza) {
		this.cantidadPieza = cantidadPieza;
	}
}
