package com.uade.seminario.tpo.view.objectView;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : itemReporte.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class ItemReporteView {
	private String nombrePieza;
	private int cantidadPieza;
	public ItemReporteView(){//No tiene vectores a inicializar
		
	}
	public ItemReporteView(String nombre, Integer cantidad) {
		this.cantidadPieza=cantidad;
		this.nombrePieza=nombre;
	}
	public String getNombrePieza() {
		return nombrePieza;
	}
	public void setNombrePieza(String nombrePieza) {
		this.nombrePieza = nombrePieza;
	}
	public int getCantidadPieza() {
		return cantidadPieza;
	}
	public void setCantidadPieza(int cantidadPieza) {
		this.cantidadPieza = cantidadPieza;
	}
}
