package com.uade.seminario.tpo.controller;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;


import com.uade.seminario.tpo.service.ClienteDataService;
import com.uade.seminario.tpo.service.EmpleadoDataService;
import com.uade.seminario.tpo.service.EquipoService;
import com.uade.seminario.tpo.service.ModeloDataService;
import com.uade.seminario.tpo.service.ReporteDataService;
import com.uade.seminario.tpo.view.objectView.ClienteView;
import com.uade.seminario.tpo.view.objectView.EquipoView;
import com.uade.seminario.tpo.view.objectView.ModeloView;
import com.uade.seminario.tpo.view.objectView.OrdenReparacionView;
import com.uade.seminario.tpo.view.objectView.PiezaView;
import com.uade.seminario.tpo.view.objectView.TareaReparacionView;
import com.uade.seminario.tpo.exceptions.ClienteNoExisteException;
import com.uade.seminario.tpo.exceptions.EmpleadoNoExisteException;
import com.uade.seminario.tpo.exceptions.EquipoNoExisteException;
import com.uade.seminario.tpo.exceptions.ExceptionExisteCliente;
import com.uade.seminario.tpo.exceptions.ExceptionExisteModelo;
import com.uade.seminario.tpo.exceptions.ExceptionModeloInactivo;
import com.uade.seminario.tpo.exceptions.ExceptionModeloPerteneceEquipo;
import com.uade.seminario.tpo.exceptions.ExceptionNoExisteModelo;
import com.uade.seminario.tpo.exceptions.GarantiaNoExisteException;
import com.uade.seminario.tpo.exceptions.ModeloExisteException;
import com.uade.seminario.tpo.exceptions.OrdenNoExisteException;
import com.uade.seminario.tpo.model.Cliente;
import com.uade.seminario.tpo.model.ClienteId;
import com.uade.seminario.tpo.model.Empleado;
import com.uade.seminario.tpo.model.Equipo;
import com.uade.seminario.tpo.model.Garantia;
import com.uade.seminario.tpo.model.ItemReporte;
import com.uade.seminario.tpo.model.Modelo;
import com.uade.seminario.tpo.model.OrdenReparacion;
import com.uade.seminario.tpo.model.Pieza;
import com.uade.seminario.tpo.model.Remito;
import com.uade.seminario.tpo.model.Reporte;
import com.uade.seminario.tpo.model.TareaReparacion;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sistema de Reparaciones.java
//  @ Date : 29/07/2013
//  @ Author : 
//
//




public class SistemadeReparaciones {
	private static SistemadeReparaciones instancia;
	private List<Remito> remitos;
	private List<Garantia> garantias;
	private List<Modelo> modelos;
	private List<Pieza> piezas;
	private List<OrdenReparacion> ordReparacion;
	private List<Equipo> equipos;
	private ArrayList<Cliente> clientes;
	private ArrayList<Empleado> empleados;
	private List<Reporte> reportes;
	
	private SistemadeReparaciones(){
		this.remitos=new ArrayList<Remito>();
		this.garantias=new ArrayList<Garantia>();
		this.modelos=new ArrayList<Modelo>();
		this.piezas=new ArrayList<Pieza>();
		this.ordReparacion=new ArrayList<OrdenReparacion>();
		this.empleados=new ArrayList<Empleado>();
		this.equipos=new ArrayList<Equipo>();
		this.clientes= new ArrayList<Cliente>();
		this.reportes=new ArrayList<Reporte>();
		
		/* CLASES PARA TEST */
		Pieza pieza= new Pieza(1, "tornillo", "es un tornillo");
		pieza.setEstado("activo");
		piezas.add(pieza);
		
		Pieza pieza2= new Pieza(2, "tuerca", "es una tuerca");
		pieza2.setEstado("activo");
		piezas.add(pieza2);
		
		Modelo modelo= new Modelo("XP","windows", 1);
		modelo.setEstado("activo");
		modelo.addPieza(pieza);
		modelos.add(modelo);
		Cliente cliente= new Cliente("1", "DNI", "mau", "Gri", "bla", "bla", "14/12/1990", "12");
		clientes.add(cliente);
		Date dia=new Date( Date.parse("12/14/1990"));
		Garantia garantia=new Garantia(1,dia);
		garantias.add(garantia);
		Equipo equipo=new Equipo(1, modelo, cliente, garantia);
		equipo.setEstado("activo");
		equipos.add(equipo);
		Equipo equipo2=new Equipo(2, modelo, cliente, garantia);
		equipo2.setEstado("activo");
		equipos.add(equipo2);
		OrdenReparacion orden=new OrdenReparacion(1);
		TareaReparacion tarea=new TareaReparacion(1, "Le falta un tornillo");
		TareaReparacion tarea1=new TareaReparacion(2, "Le faltan dos tornillos");
		tarea.agregarPieza(pieza);
		tarea.setEstado("activo");
		tarea1.agregarPieza(pieza);
		tarea1.setEstado("activo");
		orden.setDescripcionFallas("falla blabla");		
		orden.setEquipo(equipo);
		orden.setEstado("A reparar");
		orden.setEstaEnGarantiaFisica(true);
		orden.setFecha(dia);
		orden.setPrioridad(10);
		orden.setRepararDeTodosModos(true);
		orden.agregarItemReparacion(tarea);
		orden.agregarItemReparacion(tarea1);
		ordReparacion.add(orden);
		Empleado empleado=new Empleado();
		empleado.setLegajo(1);
		empleado.setaReparar(new ArrayList<OrdenReparacion>());
		empleados.add(empleado);
		
		OrdenReparacion orden1=new OrdenReparacion(2);
		TareaReparacion tarea2=new TareaReparacion(1, "Le falta una tuerca");
		TareaReparacion tarea3=new TareaReparacion(2, "Le faltan dos tuercas");
		tarea2.agregarPieza(pieza);
		tarea2.setEstado("activo");
		tarea3.agregarPieza(pieza2);
		tarea3.setEstado("activo");
		orden1.setDescripcionFallas("falla blabla");		
		orden1.setEquipo(equipo);
		orden1.setEstado("Entregado");
		orden1.setEstaEnGarantiaFisica(true);
		orden1.setFecha(dia);
		orden1.setPrioridad(8);
		orden1.setRepararDeTodosModos(true);
		orden1.agregarItemReparacion(tarea2);
		orden1.agregarItemReparacion(tarea3);
		ordReparacion.add(orden1);
		
		OrdenReparacion orden2=new OrdenReparacion(2);
		orden2.setDescripcionFallas("falla blabla");		
		orden2.setEquipo(equipo);
		orden2.setEstado("Reparado");
		orden2.setEstaEnGarantiaFisica(true);
		orden2.setFecha(dia);
		orden2.setPrioridad(9);
		orden2.setRepararDeTodosModos(true);
		orden2.agregarItemReparacion(tarea2);
		orden2.agregarItemReparacion(tarea3);
		ordReparacion.add(orden1);
		
		/* CLASES PARA TEST */
	}
	
	public static SistemadeReparaciones getInstancia(){
		if(instancia==null)
			instancia=new SistemadeReparaciones();
		return instancia;
	}
	
	public void altaModelo(ModeloView modeloView)throws ModeloExisteException{  
		try{
			buscarModelo(modeloView.getNroModelo());
			throw new ModeloExisteException(modeloView.getNroModelo());
		}catch (ExceptionNoExisteModelo e){
			AdministradorModelo.getInstancia().altaModelo(modeloView);
		}
	}
	
	public void modificarModelo(ModeloView modelo){	
		AdministradorModelo.getInstancia().modificarModelo(modelo);	
	}
	
	public void bajaModelo(int codigo) throws ExceptionModeloInactivo{
		Modelo modelo =  AdministradorModelo.getInstancia().buscarModelo(codigo);
		
		if(modelo!=null && modelo.modeloActivo()){
			if(!AdministradorEquipo.getInstancia().existeElModeloEnUnEquipo(modelo)) modelo.darBajaModelo();
			else throw new ExceptionModeloPerteneceEquipo(codigo);
		}
		else{
			if(modelo==null) throw new ExceptionNoExisteModelo(codigo);
			else throw new ExceptionModeloInactivo(codigo);			
		}
		
	}
	
	public void eliminarModelo(int codigo) {
		Modelo modelo=this.buscarModelo(codigo);
		if(modelo!=null){
			modelo.eliminar();
			modelos.remove(modelo);
		}
		
	}

	private OrdenReparacion buscarEquipoxOrdenRepAConfirmar(int nroSerieEquipo) {
		Equipo equipo = AdministradorEquipo.getInstancia().buscarEquipo(nroSerieEquipo);
		return AdministradorOrdenReparacion.getInstancia().buscarEquipoxOrdenRepAConfirmar(equipo);
	}

	public void modificarOrdenReparacion(OrdenReparacionView orden){
			AdministradorOrdenReparacion.getInstancia().modificarOrdenReparacion(orden);		
	}
	

	

	private OrdenReparacion BuscarEquipoxOrdenRep(int nroSerieEquipo) {
		for (OrdenReparacion or : ordReparacion) {
			if(or.esTuEquipo(nroSerieEquipo) && or.estadoAReparar()){
				return or;
			}
		}
		return null;
	}



	public OrdenReparacionView misReparaciones(int legajo) throws EmpleadoNoExisteException {
		Empleado empleado=AdministradorEmpleado.getInstancia().buscarEmpleado(legajo);
		if(empleado!=null){
			return AdministradorOrdenReparacion.getInstancia().asignarSiguienteOrdenReparacion(empleado);
		}
		else throw new EmpleadoNoExisteException(String.valueOf(legajo));		
	}

	private OrdenReparacion buscarOrdenReparacionPrioridad() { 
		return AdministradorOrdenReparacion.getInstancia().buscarOrdenReparacionPrioridad();
	}

	public List<TareaReparacionView> listarTareasReparacion(int nroReparacion){
		return AdministradorOrdenReparacion.getInstancia().listarTareas(nroReparacion);
		
	}
	
	public Reporte emitirReportePiezas(Date desde,Date hasta){
		return AdministradorReporte.getInstancia().generarReportePiezas(desde,hasta);
	}

//	public Reporte emitirReportePiezas(Date desde,Date hasta){
//		List<OrdenReparacionView> ordenes=buscarOrdenesReporte(desde,hasta);
//		return AdministradorReporte.getInstancia().generarReportePiezas(desde,hasta,ordenes);
//	}
//
//	public List<OrdenReparacionView> buscarOrdenesReporte(Date desde, Date hasta) {
//		return AdministradorOrdenReparacion.getInstancia().ordenesPorFecha(desde, hasta);
//	}

	
	public void altaCliente(ClienteView clienteView){
		try{
			Cliente cliente =  buscarCliente(clienteView.getNroDoc(), clienteView.getTipoDoc());
			throw new ExceptionExisteCliente(clienteView.getNroDoc());
		}catch (ClienteNoExisteException e){
			AdministradorCliente.getInstancia().AltaCliente(clienteView);
			
		}
	}
	
	private Cliente buscarCliente(String nroDoc, String tipoDoc) throws ClienteNoExisteException{
		Cliente cliente = AdministradorCliente.getInstancia().buscarCliente(nroDoc, tipoDoc); 
		if (cliente != null) return cliente;
		throw new ClienteNoExisteException(nroDoc, tipoDoc);
	}
	private Empleado buscarEmpleado(int legajo) throws EmpleadoNoExisteException{
		Empleado empleado = AdministradorEmpleado.getInstancia().buscarEmpleado(legajo);
		if (empleado != null) return empleado;
		throw new EmpleadoNoExisteException(String.valueOf(legajo));
	}
	private Equipo buscarEquipo(int nroSerieEquipo) throws EquipoNoExisteException {
		Equipo	equipo = AdministradorEquipo.getInstancia().buscarEquipo(nroSerieEquipo);
		if (equipo!=null) return equipo;
		throw new EquipoNoExisteException(String.valueOf(nroSerieEquipo));
	}
	private  Modelo buscarModelo(int codigo) throws ExceptionNoExisteModelo {
		Modelo modelo =  AdministradorModelo.getInstancia().buscarModelo(codigo);
		if (modelo!=null) return modelo;
		throw new ExceptionNoExisteModelo(codigo);		

	}
	private Pieza buscarPieza(int codPieza) {
		Pieza pieza = AdministradorPieza.getInstancia().buscarPieza(codPieza);
		if (pieza!=null) return pieza;
		throw new ExceptionNoExisteModelo(codPieza);	
		
	}

	private Garantia buscarGarantia(int nroGarantia) throws GarantiaNoExisteException{
		Garantia garantia = AdministradorGarantia.getInstancia().buscarGarantia(nroGarantia);
		if (garantia!=null) return garantia;
		throw new GarantiaNoExisteException(nroGarantia);
	}
	private  OrdenReparacion buscarOrdenReparacion(int nroReparacion) {
		OrdenReparacion ordenReparacion = AdministradorOrdenReparacion.getInstancia().
				buscarOrdenReparacion(nroReparacion);
		if (ordenReparacion!=null) return ordenReparacion;
		throw new OrdenNoExisteException(nroReparacion);
	}
	public ClienteView obtenerClienteView(String nroDoc,String tipoDoc) {
		return buscarCliente(nroDoc, tipoDoc).getView();
	}

	public void modificarCliente(String nroDoc, String tipoDoc,String nombre1, String dir, String tel,
			String mail) {
		Cliente cliente=buscarCliente(nroDoc,tipoDoc);
		cliente.setNombre(nombre1);
		cliente.setDireccion(dir);
		cliente.setTelefono(tel);
		cliente.setEmail(mail);		
	}
	public void modificarCliente(ClienteView cliente){
		AdministradorCliente.getInstancia().modificarCliente(cliente);
	}
	public void altaPieza(String nombre, int codPieza, int codModelo, String descripcion) {
		Modelo modelo=buscarModelo(codModelo);
		Pieza pieza=buscarPieza(codPieza);
		if(modelo!=null && pieza==null){
			pieza=new Pieza(codPieza,nombre,descripcion);
			modelo.addPieza(pieza);
			piezas.add(pieza);
		}
		
	}
	public void altaPieza(PiezaView pieza){
		AdministradorPieza.getInstancia().altaPieza(pieza);
	}


	public PiezaView buscarPiezaView(int codigoPieza) {
		return AdministradorPieza.getInstancia().buscarPiezaView( codigoPieza);
	}

	public void modificarPieza(PiezaView pieza) {
		AdministradorPieza.getInstancia().modificarPieza(pieza);
		
	}

	public void bajaPieza(int codigoPieza) {
		 if (!hayModelosConPieza(codigoPieza))
			 AdministradorPieza.getInstancia().bajaPieza(codigoPieza);
	}

	private boolean hayModelosConPieza(int codigoPieza) {
		Pieza pieza=AdministradorPieza.getInstancia().buscarPieza(codigoPieza);
		return AdministradorModelo.getInstancia().hayModelosConPieza(pieza);
	}

	public ModeloView buscarModeloView(int codModelo) {
		return AdministradorModelo.getInstancia().buscarModeloView(codModelo);
	}

	public List<PiezaView> buscarPiezaXModeloView(int codModelo) {
		ModeloView modelo = AdministradorModelo.getInstancia().buscarModeloView(codModelo);
		if (modelo != null)
			return modelo.getPiezas();
		return null;
	}

	public void confirmarModelo(int codigo) {
		Modelo modelo= buscarModelo(codigo);
		if(modelo!=null)
			modelo.activar();
		else
			throw new ExceptionNoExisteModelo(codigo);
		
	}
	public void altaEquipo(int nroEquipo,int nroModelo,String tipoDoc,String nroDoc,Date fecha,String nroGarantia,boolean repararDeTodosModos){
		Equipo equipo=buscarEquipo(nroEquipo);
		Modelo modelo=buscarModelo(nroModelo);
		Cliente cliente=buscarCliente(nroDoc, tipoDoc);
		Garantia garantia1=null;
		if(!nroGarantia.equals(""))
			garantia1=buscarGarantia(Integer.parseInt(nroGarantia));
		if(equipo==null && modelo!=null && cliente!=null){
			equipo=new Equipo(nroEquipo,modelo,cliente,garantia1);
		}
		
	}


	public void altaGarantia(int nroGarantia, Date fecha1) {
		Garantia garantia=buscarGarantia(nroGarantia);
		if(garantia==null){
			garantia=new Garantia(nroGarantia,fecha1);
			garantias.add(garantia);
		}
	}

	public void quitarPiezaModelo(int codigoModelo, int nroPieza) {
		Modelo modelo=buscarModelo(codigoModelo);
		Pieza pieza=buscarPieza(nroPieza);
		if(modelo!=null && pieza!=null){
			modelo.quitarPieza(pieza);
		}
		
	}

	public void agregarPiezaModelo(PiezaView piezaV, int codigoModelo) {
		Modelo modelo=buscarModelo(codigoModelo);
		Pieza pieza=buscarPieza(piezaV.getNroPieza());
		if(modelo!=null && pieza!=null){
			modelo.addPieza(pieza);
		}
		
	}

	public EquipoView buscarEquipoView(int nroSerie) {
		Equipo equipo=buscarEquipo(nroSerie);
		if(equipo!=null && equipo.estaActivo()){
			EquipoView equipoV=equipo.getView();
			return equipoV;
		}
		else
			return null;
	}

	public OrdenReparacionView buscarOrdenConEquipoARepararView(EquipoView equipoView) {
		Equipo equipo=AdministradorEquipo.getInstancia().buscarEquipo(equipoView.getNroSerie());
		return AdministradorOrdenReparacion.getInstancia().buscarOrdenConEquipoARepararView(equipo);
		
	}

	public int obtenerNroOrdenReparacion() {
		
		return (ordReparacion.size()+1);
	}

	public List<TareaReparacionView> buscarTareasXOrdenReparacionView(int nroOrdenReparacion) {
		List<TareaReparacionView> tareasview=new ArrayList<TareaReparacionView>();
		 OrdenReparacion orden=buscarOrdenReparacion(nroOrdenReparacion);
		 if(orden!=null){
			 List<TareaReparacion> tareas=orden.getItemsReparacion();
			 for (TareaReparacion t : tareas) {
				 if(t.estaActiva())
					 tareasview.add(t.getView());				
			}
		 }
		 return tareasview;
	}

	public OrdenReparacionView buscarOrdenReparacionView(int nroOrden) {
		OrdenReparacion orden=buscarOrdenReparacion(nroOrden);
		if(orden!=null){
			return orden.getView();			
		}
		return null;
	}

	public int crearTareaReparacion(String descripcion, int numeroOrden) {
		OrdenReparacion orden=buscarOrdenReparacion(numeroOrden);
		if(orden!=null && !orden.getEstado().equals("Reparado")){
			int numeroTarea=obtenerNumeroTarea(orden);
			TareaReparacion tarea=new TareaReparacion(numeroTarea, descripcion);
			orden.agregarItemReparacion(tarea);
			return numeroTarea;
		}
		return 0;
		
	}

	private int obtenerNumeroTarea(OrdenReparacion orden) {
		return orden.getItemsReparacion().size()+1;
	}

	public List<PiezaView> buscarPiezasXTareaView(int nroOrden, int nroTarea) {
		List<PiezaView> piezas=new ArrayList<PiezaView>();
		OrdenReparacion orden=buscarOrdenReparacion(nroOrden);
		if(orden!=null){
			TareaReparacion tarea=orden.obtenerTarea(nroTarea);
			if(tarea!=null){
				for (Pieza pieza : tarea.getPiezas()) {
					if(pieza.estaActiva())
					piezas.add(pieza.getView());
				}
			}
		}
		return piezas;
	}

	public void agregarPiezaTarea(int nroOrden, int nroTarea, int nroPieza) {
		OrdenReparacion orden=buscarOrdenReparacion(nroOrden);
		Pieza pieza=buscarPieza(nroPieza);
		if(orden!=null){
			TareaReparacion tarea= orden.obtenerTarea(nroTarea);
			if(tarea!=null){
				tarea.agregarPieza(pieza);
			}
		}
		
		
	}

	public void quitarPiezaTarea(int nroOrden, int nroTarea, int nroPieza) {
		OrdenReparacion orden=buscarOrdenReparacion(nroOrden);
		Pieza pieza=buscarPieza(nroPieza);
		if(orden!=null){
			TareaReparacion tarea= orden.obtenerTarea(nroTarea);
			if(tarea!=null){
				pieza.setEstado("inactivo");
			}
		}
		
	}

	public void quitarTareaOrdenReparacion(int nroOrden, int nroTarea) {
		OrdenReparacion orden=buscarOrdenReparacion(nroOrden);
		if(orden!=null){
			TareaReparacion tarea=orden.obtenerTarea(nroTarea);
			if(tarea!=null && tarea.estaActiva()){
				tarea.setEstado("inactivo");
			}
		}
		
	}
	public void confirmarOrdenReparacion(OrdenReparacionView orden ){
		AdministradorOrdenReparacion.getInstancia().confirmarOrdenReparacion(orden);
	}
	
}